### ISSUE TITLE
Use a state variable instead of a mapping

### ISSUE THREAD

**Issue by hrkrshnn** [devanonon/GenericERC721#1]
https://github.com/devanonon/GenericERC721/blob/6bb354810024fadbb7bb1753edc81a5e97cf6c93/src/SingleNFT.sol#L7

Since it's a 1 of 1, NFT, the owner can simply be a `address owner` state variable. This saves gas, for both minting (the important part), and transfers.

**Comment by hrkrshnn** [comment]
The same can be done for `ownerOf`.

**Comment by devanoneth** [comment]
Thanks! I'm just wondering if Opensea would use these mappings, but I guess they probably just rely on the events. 

If they do only rely on events, I guess we could just remove these mappings and thus state variables all together?

**Comment by hrkrshnn** [comment]
Opensea, etc, should only rely on the EIP. Which requires the function `balanceOf` to be present. How it stores the data is not relevant.

**Comment by devanoneth** [comment]
Good point! I've implemented your suggestion, saved a lot of gas, thanks @hrkrshnn!
